export const pokemonConstants = {
  GET_POKEMON_LIST_REQUEST: "GET_POKEMON_LIST_REQUEST",
  GET_POKEMON_LIST_FAILURE: "GET_POKEMON_LIST_FAILURE",
  GET_POKEMON_LIST_SUCCESS: "GET_POKEMON_LIST_SUCCESS",
};

export const cartConstants = {
  ADD_CART_LIST: "ADD_CART_LIST",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
};

export const productConstants = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
};